### ISSUE TITLE
storybook docs

### ISSUE THREAD

**Issue by banzaiMimic** [pipeDr3am/simplifa11y#12]
double check all possible params are displayed with their default values if any (some are missing)

**Comment by Shamik1836** [comment]
Hey, I would like to add on this, can u please elaborate the point u are trying to make?

**Comment by banzaiMimic** [comment]
@Shamik1836 hi thanks I am nearly done with this issue, this project is still not in a state to be 'fully released' to public just yet sorry for the confusion . i have added the appropriate tags and assigned the issues to myself while I finish getting things ready for an acceptable public release. feel free to help test the 0.0.7-rc.0 version though Thanks again!

**Comment by banzaiMimic** [comment]
ended up replacing storybook for barebones doc page
